### ISSUE TITLE
Cant configure gaffer plugin in deadline

### ISSUE THREAD

**Issue by Kaiz3rTool** [hypothetical-inc/GafferDeadline#3]
hello, when opening the plugins configuration menu deadline monitor as super user, 
the gaffer plugins shows : 

> there are no configurable settings for this plugin

nothing can be configurated from this
gaffer.param point to the exact version number of gaffer and the deadline dispatcher appear in gaffer, as expected

OS : CENTOS 7
deadline version : 10.0.26
gaffer version : 0.53.6.0

**Comment by ericmehl** [comment]
It sounds like you may have modified the gaffer.param file to change the Gaffer version to 0.53.6.0, is that correct? Can you upload the gaffer.param file here and I can try it out? Maybe there's a syntax error that is causing Deadline to not load the settings.

**Comment by Kaiz3rTool** [comment]
Hi, thank you
here is my param file
`[About]
Type=label
Label=About
Category=About Plugin
CategoryOrder=-1
Index=0
Default=Gaffer for Deadline
Description=Not configurable

[ConcurrentTasks]
Type=label
Label=ConcurrentTasks
Category=About Plugin
CategoryOrder=-1
Index=0
Default=True
Description=Not configurable.

[Executable0_45_0_0]
Type=multilinemultifilename
Category=Gaffer 0.45.0.0 Executables
CategoryOrder=0
CategoryIndex=0
Label=Gaffer 0.45.0.0 Render Executable
Default=%HOME%/gaffer_0.45.0.0;~/gaffer_0.45.0.0
Description=The path to the Gaffer 0.45.0.0 executable (gaffer.bat on Windows) file used for executing. Enter alternative paths on separate lines.
[Executable0_53_6_0]
Type=multilinemultifilename
Category=Gaffer 0.53.6.0 Executables
CategoryOrder=0
CategoryIndex=0
Label=Gaffer 0.53.6.0 Render Executable
Default=%HOME%/gaffer_0.53.6.0;~/gaffer_0.53.6.0
Description=The path to the Gaffer 0.53.6.0 executable (gaffer.bat on Windows) file used for executing. Enter alternative paths on separate lines.

[EnablePathMapping]
Type=boolean
Category=Path Mapping (For Mixed Farms)
CategoryOrder=70
CategoryIndex=0
Label=Enable Path Mapping
Default=true
Description=If enabled, environment variables will be set for the process running Gaffer. This feature can be turned off if there are no Path Mapping entries defined in the Repository Options.
`

**Comment by ericmehl** [comment]
That's weird, I pasted your text into my gaffer.param and it's working fine for me. Try unzipping the attached file and copying the gaffer.param, and give it a try. 

Just to double check, you should have the following files in the <DeadlineRepository>/custom/plugins/Gaffer directory:
* gaffer.ico
* gaffer.options
* gaffer.param
* gaffer.py

Are all of those in place? Are the owner and permissions set to allow you access? Try setting permissions to 777 if they are not already and see if that helps.

[gaffer.zip](https://github.com/hypothetical-inc/GafferDeadline/files/3314648/gaffer.zip)

**Comment by Kaiz3rTool** [comment]
it's work fine from your zip, thank you 
maybe I have some kind of invisible things in mine that corrupt it... not sure to understand but, hey, it work !

**Comment by ericmehl** [comment]
Great to hear it worked! I suspect it might be a unicode problem - I've run into some other parts of Deadline that give me errors with that. When you need to change / add a version in the future check if your text editor is defaulting to unicode or something similar.

**Comment by Kaiz3rTool** [comment]
Hi, 
finally the problem is still present on linux, even with your file or the orginal one unedited (both are in unicode)
strangely, it work in deadline monitor from windows, even if the file is set in unicode Unix (both OS pointing the the exact same repo / plugin)

the problem is if I setup gaffer parameter from windows then try a render on a linux box, it will not work and deadline return the error :
"fail after 4 attempt to copy gaffer.param. Please make sure the file exist in plugin directory"
the file exist and have permission set to 777

**Comment by ericmehl** [comment]
It turns out to be a bone-headed mistake on my part - all of the files in the Gaffer plugin directory need to have a capital G, so Gaffer.options, Gaffer.param, etc.

I'll make the change in just a minute and push an update to the repository. If see this before I update it, try changing those file names to be capitalized and see if it solves it for you.
