### ISSUE TITLE
Job Name on DeadlineDispatcher ignored

### ISSUE THREAD

**Issue by arvidurs** [hypothetical-inc/GafferDeadline#80]
The job name is not being set on the deadline monitor, instead it used the name of the actual render node. 
I would like to suggest, that the Job name should be working, and the name of the Render node could be a suffix. 
like this: 

jobName_Render or 
jobName_ImageWriter 

or something like that.

**Comment by ericmehl** [comment]
Completed in https://github.com/hypothetical-inc/GafferDeadline/commit/71b29de24e833e450fffcfc08cf08f32eca6f036
