### ISSUE TITLE
log from failed job isn't available

### ISSUE THREAD

**Issue by Kaiz3rTool** [hypothetical-inc/GafferDeadline#9]
When an error appear in deadline, the log is not available in the job reports and the task log. Deadline return :

`Error: Unexpected error getting report log /mnt/FarmRepo/DeadlineRepository10/reports/jobs/a2/4/5d349c0091ee254d552efa24/5d349fd191ee257634e1e293.bz2: Access to the path "/mnt/FarmRepo/DeadlineRepository10/reports/jobs/a2/4/5d349c0091ee254d552efa24/5d349fd191ee257634e1e293.bz2" is denied.`

Centos 7.6
deadline repo and client version 10.0.27.3
Gaffer 0.53.6.0

**Comment by ericmehl** [comment]
Can you check that the .bz2 file exists and see what the permissions are? Does this only happen with failed jobs or do successful jobs miss that too?

I'll recreate a failed GafferDeadline job tomorrow to see what I can discover.

Side note: I've had these crop up especially when accessing the farm remotely through VPN where I wasn't logged in quite right or don't have the right paths mounted correctly. Might be something to double check.

**Comment by ericmehl** [comment]
Sorry for the delay looking into this. I'm not able to recreate the situation where the log can't be found - I tried a simple PythonCommand node that did a divide by zero `a=5/0` to trigger an error and I see the logs ok in Deadline.

Are you able to share the Gaffer script that is causing this? If not, can you describe in general what the script does and what nodes it is using? Maybe that's part of it.

**Comment by Kaiz3rTool** [comment]
hi, sorry for the late answer, yes the file exist, permission are not set as expected (770) 
seems to be more a deadline problem than a gafferdeadline one, i will investigate on it, thanks
